# This is a basic workflow to help you get started with Actions

name: Deploy Infrastructure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tf_fmt:
    name: Fullstack Test1
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: setup npm     
      uses: actions/setup-node@v3
      with:
         node-version: 15    

    - name: Install npm
      id: fmt
      run: pwd && ls -lart && cd rdicidr-0.1.0 && npm install
      continue-on-error: true
      
