# This is a basic workflow to help you get started with Actions

name: Deploy Infrastructure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tf_fmt:
    name: Fullstack Test1
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: setup npm     
      uses: actions/setup-node@v3
      with:
         node-version: 15    

    - name: Install npm
      id: install
      run: cd rdicidr-0.1.0 && npm install
      continue-on-error: true

    - name: npm lint
      id: lint
      run: cd rdicidr-0.1.0 &&  npm run lint
      continue-on-error: true

    - name: npm prettier
      id: prettier
      run: cd rdicidr-0.1.0 && npm run prettier
      continue-on-error: true

    - name: npm Jest testcases
      id: testcases
      run: cd rdicidr-0.1.0 && CI=true && npm run test
      continue-on-error: true

    - name: npm build
      id: buildnpm
      run: cd rdicidr-0.1.0 && npm run build
      continue-on-error: true                
      
